### ISSUE TITLE
reference to old github URL causes gb to download the package twice

### ISSUE THREAD

**Issue by stevewritescode** [educlos/testrail#13]
This line references what appears to be an old URL for this repo "github.com/Etienne42/testrail": https://github.com/educlos/testrail/blob/master/testrail-generate/main.go#L6

The causes gb to download essentially the same repo twice:
```
$ gb vendor fetch https://github.com/educlos/testrail
fetching recursive dependency github.com/Etienne42/testrail
```

**Comment by educlos** [comment]
Indeed, I forgot to update this line. Thanks
