### ISSUE TITLE
Where is the template id in add case?

### ISSUE THREAD

**Issue by yamunadevins** [educlos/testrail#17]
Hi,
I am trying to automate the add case, how to pass Template id in sendable case

Regards,
Yamuna

**Comment by educlos** [comment]
Hi Yamuna,
It looks like template id were added after I wrote this part (it's been a while now).
I could add it. but I don't have a testrail account anymore to test if the changes will work or not.

**Comment by yamunadevins** [comment]
@educlos Could you please add template id?

**Comment by educlos** [comment]
I [added it](https://github.com/educlos/testrail/commit/363fd958d1dfda59686bc78ff4e7ab51573ce1d2), please validate that it works as I cannot test against a real testrail.

**Comment by yamunadevins** [comment]
Template id is added now, hence closing the issue
