### ISSUE TITLE
custom_test_description needs to be added in add case which is mandatory field

### ISSUE THREAD

**Issue by yamunadevins** [educlos/testrail#18]
custom_test_description needs to be added in add case which is mandatory field

**Comment by educlos** [comment]
I don't see it as a possible field on the documentation: http://docs.gurock.com/testrail-api2/reference-cases#add_case

**Comment by yamunadevins** [comment]
@educlos  you can see it in custom field. Because of this , i am unable to add a case using this package , but i am able to do using RESTAPIs directly , when i add the field custom_test_description it is passing , else it is failing stating custom_step_description is mandatory , even consulted with testrail team.

**Comment by educlos** [comment]
The problem with custom fields is that they are custom, and what is mandatory on your side might not exist for an other user of testrail.
The solution would be that you fork the repo and add your own custom fields on it.

**Comment by yamunadevins** [comment]
@educlos is it possible to add custom_test_description as it is mandatory for many projects , rest of optional fields , i will fork the project and use it

**Comment by yamunadevins** [comment]
@educlos any updtes on the same?

**Comment by yamunadevins** [comment]
There are lot of optional fields in sendable case, it would be great if you can add custom_test_description too
	
       Checkbox    bool         `json:"custom_checkbox,omitempty"`
	Date        string       `json:"custom_date,omitempty"`
	Dropdown    int          `json:"custom_dropdown,omitempty"`
	Integer     int          `json:"custom_integer,omitempty"`
	Milestone   int          `json:"custom_milestone,omitempty"`
	MultiSelect []int        `json:"custom_multi-select,omitempty"`
	Steps       []CustomStep `json:"custom_steps,omitempty"`
	String      string       `json:"custom_string,omitempty"`
	Text        string       `json:"custom_text,omitempty"`
	URL         string       `json:"custom_url,omitempty"`
	User        int          `json:"custom_user,omitempty"`

**Comment by educlos** [comment]
It's been added to `SendableCase` on [this commit](https://github.com/educlos/testrail/commit/488f9e3f1948569cdbd8a07cc77e81ef579d1812).
