### ISSUE TITLE
Support querying TestRail with pagination

### ISSUE THREAD

**Issue by renzors** [educlos/testrail#25]
Since TestRail 6.7, they introduced pagination in their APIs. This will impact this package as it is expecting to get all the info from TestRail in single API call before processing.

The full list of bulk API endpoints that include this change are below:

get_cases
get_runs
get_results
get_tests
get_results_for_case
get_results_for_run
get_plans
get_projects
get_sections
get_milestones
get_history_for_case
get_attachments_for_case
get_attachments_for_run
get_attachments_for_plan

These bulk endpoints will no longer return an array of all entities, but will instead return an object with additional pagination fields and an array of up to 250 entities. We will need to update the package according to the new response structure to support new version.

Announcing reference: https://blog.gurock.com/announcing-testrail-6-7/

**Comment by educlos** [comment]
Closed by https://github.com/educlos/testrail/pull/26
